version: '3'
services:
   db:
    container_name: postgres
    image: postgres:9.6
    ports:
      -${DATABASE_PORT}:5432
    environment:
      POSGRES_USER:${DATABASE_USER}
      POSGRES_PASSWD:${DATABASE_PASSWORD}
      POSGRES_DB:${DATABASE_DB}
      
    volumes:
      -./pgdata:/var/lib/postgresql/data

volumes:
      pgdata